# Generated by Django 5.1.3 on 2024-11-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luma07',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('classification', models.CharField(choices=[('GENERAL FOREMAN', 'GENERAL FOREMAN'), ('CREW LEADER', 'CREW LEADER')], max_length=50)),
                ('area', models.CharField(choices=[('ARECIBO 1', 'ARECIBO 1'), ('ARECIBO 2', 'ARECIBO 2'), ('ARECIBO 3', 'ARECIBO 3'), ('ARECIBO 4', 'ARECIBO 4'), ('SAN JUAN', 'SAN JUAN'), ('HERBICIDA', 'HERBICIDA'), ('SUB ESTACIONES', 'SUB ESTACIONES'), ('VINES', 'VINES'), ('MAYAGUEZ 1', 'MAYAGUEZ 1'), ('MAYAGUEZ 2', 'MAYAGUEZ 2')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('dispositivo', models.CharField(choices=[('Ipad', 'Ipad'), ('Tablet', 'Tablet')], max_length=10)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('sim_card', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('puerto_de_carga', models.CharField(choices=[('USB-C', 'USB-C'), ('Lightning', 'Lightning')], max_length=50)),
                ('tag_id', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[('07', '07'), ('30', '30'), ('REC', 'REC'), ('DTOP', 'DTOP'), ('EDUCACION', 'EDUCACION'), ('ORNATO', 'ORNATO'), ('IT', 'IT'), ('ORQUIDEA', 'ORQUIDEA'), ('OFICINA', 'OFICINA')], max_length=50)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
