# Generated by Django 5.1.3 on 2024-11-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_id', models.CharField(choices=[('07', '07'), ('30', '30'), ('REC', 'REC'), ('DTOP', 'DTOP'), ('EDUCACION', 'EDUCACION'), ('ORNATO', 'ORNATO'), ('IT', 'IT'), ('ORQUIDEA', 'ORQUIDEA'), ('OFICINA', 'OFICINA'), ('TODOS', 'TODOS')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_id', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('classification', models.CharField(choices=[('GENERAL FOREMAN', 'GENERAL FOREMAN'), ('CREW LEADER', 'CREW LEADER')], max_length=50)),
                ('area', models.CharField(choices=[('ARECIBO 1', 'ARECIBO 1'), ('ARECIBO 2', 'ARECIBO 2'), ('ARECIBO 3', 'ARECIBO 3'), ('ARECIBO 4', 'ARECIBO 4'), ('SAN JUAN', 'SAN JUAN'), ('HERBICIDA', 'HERBICIDA'), ('SUB ESTACIONES', 'SUB ESTACIONES'), ('VINES', 'VINES'), ('MAYAGUEZ 1', 'MAYAGUEZ 1'), ('MAYAGUEZ 2', 'MAYAGUEZ 2')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('dispositivo', models.CharField(choices=[('Ipad', 'Ipad'), ('Tablet', 'Tablet')], max_length=10)),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('sim_card', models.CharField(max_length=20, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('puerto_de_carga', models.CharField(choices=[('USB-C', 'USB-C'), ('Lightning', 'Lightning')], max_length=50)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tabletas.departamento')),
            ],
            options={
                'unique_together': {('departamento_id', 'tag_id')},
            },
        ),
    ]
