# Generated by Django 5.1.3 on 2024-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewTablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('classification', models.CharField(choices=[('classification_1', 'General Foreman '), ('classification_2', 'Crew Leader')], max_length=50)),
                ('area', models.CharField(choices=[('area_1', 'ARECIBO 1'), ('area_2', 'ARECIBO 2'), ('area_3', 'ARECIBO 3'), ('area_4', 'ARECIBO 4'), ('area_5', 'SAN JUAN'), ('area_6', 'HERBICIDA'), ('area_7', 'SUB ESTACIONES'), ('area_8', 'VINES'), ('area_9', 'MAYAGUEZ 1'), ('area_10', 'MAYAGUEZ 2')], max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('dispositivo', models.CharField(choices=[('Ipad', 'Ipad'), ('Tablet', 'Tablet')], max_length=10)),
                ('imei', models.CharField(max_length=20)),
                ('sim_card', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('puerto_de_carga', models.CharField(choices=[('puerto_1', 'USB-C'), ('puerto_2', 'Lightning')], max_length=50)),
                ('tag_id', models.CharField(max_length=50)),
                ('departamento', models.CharField(choices=[('departamento_1', '07'), ('departamento_2', '30'), ('departamento_3', 'REC'), ('departamento_4', 'DTOP'), ('departamento_5', 'EDUCACION'), ('departamento_6', 'ORNATO')], max_length=50)),
                ('last_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
