# Generated by Django 5.1.3 on 2024-11-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tabletas', '0002_departamento'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Luma07',
            new_name='Tabletas',
        ),
    ]
